### PR TITLE
Don't use Yajl's JSON gem compat API

### LINKED ISSUE #27: splunkhec plugin completely breaks fluentd graceful reloads - Failed to reload config file: expected end of line
### Describe the bug

Trying to gracefully reload fluentd with a super simple configuration that is using splunkhec plugin and getting a syntax error, while there is no visible errors in the syntax.

### To Reproduce

Try to reload (https://docs.fluentd.org/deployment/signals#sigusr2) fluentd with the simple config I have provided.

### Expected behavior

Loading of splunkhec plugin shouldn't cause fluentd to generate a config syntax error on graceful reload.

### Your Environment

```markdown
- Fluentd version: v1.14.1
- Operating system: Ubuntu 20.04
- Kernel version: 5.4.0-42-generic
```

### Your Configuration
```
<system>
  log_level info
  rpc_endpoint 127.0.0.1:24444
</system>
<source>
  @type systemd
  @id in_systemd_kubelet
  matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  <storage>
    @type local
    persistent true
    path /var/log/kube-fluentd-operator-fluentd-journald-kubelet-cursor.json
  </storage>
  <entry>
    fields_strip_underscores true
  </entry>
  read_from_head true
  tag kubelet
</source>
<match kube.example.**>
  @type splunkhec
  host splunk.example.com
  token BAB747F3-744E-41BA
</match>
```

### Your Error Log

```shell
2021-10-13 00:07:50 +0000 [info]: Reloading new config
2021-10-13 00:07:50 +0000 [error]: Failed to reload config file: expected end of line at fluent.conf line 8,12
  7:   @id in_systemd_kubelet
  8:   matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]

     ------------^
  9:   <storage>
```
```


### Additional context
Using splunkhec 2.0 plugin (https://rubygems.org/gems/fluent-plugin-splunkhec/versions/2.0).

### PR DESCRIPTION
**Pull request by ashie**
It breaks functionality of Fluentd and other plugins:

  * https://github.com/fluent/fluentd/issues/3530

And it's not maintained well:

  * https://github.com/brianmario/yajl-ruby/issues/123#issuecomment-26183655

Fix #27

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Review by Cryptophobia — APPROVED** [review]
lgtm!

**Review by alex-vmw — APPROVED** [review]
lgtm!

**Comment by Cryptophobia** [comment]
@cmeerbeek , thank you for merging this fix in! Will you be able to make a new rubygems release soon with the fix?

**Comment by cmeerbeek** [comment]
I will try to do that soon. However, I am still wondering if I should not archive this repo. There are better plugins from Splunk itself no?

**Comment by alex-vmw** [comment]
@cmeerbeek Do not archive this yet please. Official Splunk plugin is also broken at this time (see https://github.com/splunk/fluent-plugin-splunk-hec/issues/187).

**Comment by Cryptophobia** [comment]
Yes, @alex-vmw is right. He reported bugs with two of the splunk plugins . Looks like this one and the official splunk pluin both break fluentd currently. If you can make release soon, we can turn back on this splunk plugin in `v1.16.1` of [KFO](https://github.com/vmware/kube-fluentd-operator).

This is the reason I ask about a new rubygem version.

**Comment by cmeerbeek** [comment]
The 2.1 gem is published. Can you check if its OK like this?

**Comment by Cryptophobia** [comment]
@cmeerbeek , thank you for publishing the new gem version 2.1. 

We have tested on our side and it does not cause the same issues as before. This means at least the previous problems related to the plugin causing fluentd to crash are not there now. So from that standpoint, the gem has been fixed. 🙇‍♂️

**Pull request merged**
