### PR TITLE
Add raw logs to Splunk

### PR DESCRIPTION
**Pull request by bbruun**
I've added a `usejson` config parameter (default to true) which can be set to `false` which will allow the parser to add a `time` entry either from the `<source>` from a named format regex or a filter before the splunkhec `<match ...>`.

My company is looking into fluent collectors for many reasons and we use Splunk and Log4J (lots of Java) with millisecond precission eg `%Y-%m-%d %H:%M:%S,%3N` in our log entries. This needs to be preserved in Splunk as the latency and lack of precision from fluentd or the plugin is not usable.

I'm not a ruby guy so perhaps a review would be in order!

### CODE REVIEW

**Comment by bbruun** [comment]
I've updated the pull request as there were trouble with multiline 'in_tail' that was malformed.

**Comment by cmeerbeek** [comment]
Hi @bbruun. I've just merged the other PR that was open. I think it does the same thing. Can you verify your code with the latest version?
Sorry and thanks!

**Comment by bbruun** [comment]
Hi @cmeerbeek 
The other PR adds support for the log entry being a full JSON object so they are quite opposite of each other as the 'time' is taken from the log entry in this and used instead of the 'time' set by the out_splunkhec plugin and then sends the entire log entry to Splunk as "one line" (which can span multiple lines).

**Comment by bbruun** [comment]
@cmeerbeek I've tested the updated version of this PR and it works without conflicts with the other PR you pulled.

**Pull request merged**
